# ─────────────────────────────────────────────
# Walker Configuration (Refactored)
# ─────────────────────────────────────────────

# General settings
close_when_open = true
theme = "omarchy-default"
theme_base = []                          # Optional: fallback themes
theme_location = ["~/.local/share/omarchy/default/walker/themes/"]
hotreload_theme = true
force_keyboard_focus = true

# ────────────────────────── Keybindings ──────────────────────────
[keys.ai]
# Run the last AI response using Ctrl+E
run_last_response = ["ctrl e"]

# ────────────────────────── List Settings ──────────────────────────
[list]
# Maximum number of entries shown in lists
max_entries = 200

# ────────────────────────── Search Settings ──────────────────────────
[search]
placeholder = " Search..."

# ────────────────────────── Builtins ──────────────────────────

# Hyprland keybinds
[builtins.hyprland_keybinds]
path = "~/.config/hypr/hyprland.conf"
hidden = true   # Hidden in Walker to reduce clutter

# Applications
[builtins.applications]
launch_prefix = "uwsm app -- "
placeholder = " Search..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
icon = ""
hidden = true

[builtins.applications.actions]
enabled = false
hide_category = true

# Bookmarks
[builtins.bookmarks]
hidden = true

[[builtins.bookmarks.entries]]
label = "Omarchy - Github"
url = "https://github.com/basecamp/omarchy"
keywords = ["omarchy", "github"]

[[builtins.bookmarks.entries]]
label = "Omarchy Manual"
url = "https://manuals.omamix.org/2/the-omarchy-manual"
keywords = ["omarchy"]

# Calculator
[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3
prefix = "="

# Finder
[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = true
hidden = false   # Visible in Walker
prefix = "."

# Clipboard, Commands, Runner, SSH, Websearch, Translation, Custom Commands
# Hidden to keep Walker minimal
[builtins.clipboard]
hidden = true

[builtins.commands]
hidden = true

[builtins.custom_commands]
hidden = true

[builtins.runner]
shell_config = ""
switcher_only = true
hidden = true

[builtins.ssh]
hidden = true

[builtins.websearch]
switcher_only = true
hidden = true

[builtins.translation]
hidden = true

# Emojis
[builtins.emojis]
name = "Emojis"
icon = ""
prefix = ":"

# Symbols
[builtins.symbols]
after_copy = ""
hidden = true
