general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = $HOME/Pictures/wallpaper/24.png
    blur_size = 4
    blur_passes = 3 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = $color13
    font_size = 180
    font_family = JetBrainsMono Nerd Font ExtraBold 
    position = 0, -100
    halign = center
    valign = top
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $color12
    font_size = 180
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -450
    halign = center
    valign = top
}

# Seconds-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
    color = $color11
    font_size = 50
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -400
    halign = center
    valign = top
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 40
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1
    rounding = 22
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(255, 255, 255, 0.9)
    font_color = $color13
    capslock_color = rgb(255,255,255)
    fade_on_empty = true
    font_family = JetBrainsMono Nerd Font ExtraBold 
    placeholder_text = <i>PASSWORD<span foreground="##ffffff99"></span></i>
    hide_input = false
    position = 0, 100
    halign = center
    valign = bottom
}
