### WALLPAPER SETTINGS ###

# Preload wallpapers for faster switching
preload = $HOME/Pictures/wallpaper/p_o_c_k_e_t___t_o_w_n_by_dmitryalexander_dg6w3t3.png
preload = $HOME/Pictures/wallpaper/wallhaven-5g5p23_2560x1440.png


# Set wallpaper for all monitors
wallpaper = eDP-1,/home/masubhaat/Pictures/wallpaper/p_o_c_k_e_t___t_o_w_n_by_dmitryalexander_dg6w3t3.png
wallpaper = HDMI-A-1,/home/masubhaat/Pictures/wallpaper/wallhaven-5g5p23_2560x1440.png

### DISPLAY SETTINGS ###
# Enable splash screen
splash = false

# Enable wallpaper transitions
transition = true
transition_duration = 0.5
transition_fps = 60
transition_type = fade
