### GENERAL SETTINGS ###

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

### COLOR DEFINITIONS ###
# Catppuccin Mocha Theme
$color1 = rgb(180, 190, 254)  # Lavender
$color2 = rgb(137, 180, 250)  # Blue
$color3 = rgb(203, 166, 247)  # Mauve
$color4 = rgb(245, 194, 231)  # Pink
$color5 = rgb(250, 179, 135)  # Peach
$color6 = rgb(249, 226, 175)  # Yellow
$color7 = rgb(166, 227, 161)  # Green
$color8 = rgb(137, 220, 235)  # Teal
$color9 = rgb(243, 139, 168)  # Red
$color10 = rgb(205, 214, 244) # Text
$color11 = rgb(180, 190, 254) # Lavender
$color12 = rgb(137, 180, 250) # Blue
$color13 = rgb(203, 166, 247) # Mauve
$color14 = rgb(245, 194, 231) # Pink
$color15 = rgb(250, 179, 135) # Peach
$color16 = black
$color17 = rgb(255,255,255)
$color18 = rgb(165,42,42)
$color19 = rgb(128,128,128)
$color20 = rgb(255,102,102)

### BACKGROUND SETTINGS ###
background {
    monitor =
    path = $HOME/Pictures/wallis/3x.jpg 
    blur_size = 2 
    blur_passes = 2 
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

### TIME DISPLAY ###
# Hour
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = $color17
    font_size = 180
    font_family = JetBrainsMono Nerd Font ExtraBold 
    position = 0, -100
    halign = center
    valign = top
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $color17 
    font_size = 180
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -450
    halign = center
    valign = top
}

# Seconds
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
    color = $color17 
    font_size = 50
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -400
    halign = center
    valign = top
}

### PASSWORD INPUT ###
input-field {
    monitor =
    size = 200, 40
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.1
    dots_center = true
    dots_rounding = -1
    rounding = 22
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = black

    font_color = black
    capslock_color = rgb(255,255,255)
    fade_on_empty = true
    font_family = JetBrainsMono Nerd Font ExtraBold 
    placeholder_text = <i>PASSWORD<span foreground="##000000"></span></i>
    hide_input = false
    position = 0, 100
    halign = center
    valign = bottom
}
