#---------------------WALLPAPER SETTINGS----------------------#

# Preload wallpapers for faster switching
preload = $HOME/Pictures/wallis/build.png 
preload = $HOME/Pictures/wallis/1x.jpg 

# Set wallpaper for individual monitors
wallpaper = eDP-1,/home/masubhaat/Pictures/wallis/build.png 
wallpaper = HDMI-A-1,/home/masubhaat/Pictures/wallis/1x.jpg 

### DISPLAY SETTINGS ###

# Enable splash screen
splash = false

# Enable wallpaper transitions
transition = true
transition_duration = 0.8
transition_fps = 60
transition_type = fade
