# CURSOR SETTINGS
cursor {
    no_hardware_cursors = true
}


# Use defaults Omarchy defaults
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/looknfeel.conf
source = ~/.config/hypr/configs/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

