# INPUT SETTINGS 
input {
    kb_layout = us
    follow_mouse = 1
    
    # Keyboard Settings
    repeat_rate = 50
    repeat_delay = 250
    sensitivity = 0.5
    accel_profile = flat

    # Touchpad Settings
    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
        scroll_factor = 1.0
    }
}

# GESTURES
gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 300
    workspace_swipe_invert = false
    workspace_swipe_min_speed_to_force = 30
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_create_new = true
}
