# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland

# For nvidia optimization
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

xwayland {
  force_zero_scaling = true
}

# Make .desktop files available for wofi
env = XDG_DATA_DIRS,/usr/share:/usr/local/share:~/.local/share

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}

# hyprcursor
env = HYPRCURSOR_THEME, Bibata-Modern-Ice
env = HYPRCURSOR_SIZE , 15
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SCANOUT,0
env = WLR_DRM_NO_ATOMIC,1

# Extra env variables
env = GDK_SCALE,1      # Change to 1 if on a 1x display
