### CLIPBOARD HISTORY ###
#########################

exec-once = wl-paste --watch cliphist store
exec-once = wl-clipboard-history -t
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data


##################
### IMPORTANT EXECS ###
##################

exec-once = xdm-app
exec-once = hyprpanel &
exec-once = hyprpaper
exec-once = hypridle
exec-once = /usr/lib/polkit-1/polkitd
exec-once = hyprctl setcursor Bibata-Modern-Ice 15

####################
### STARTUP APPS ###
####################

exec-once = nm-applet
exec-once = blueman-applet
